// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD236s5J7NxvDWIwlAzbYzyIvMV-gsS6YY',
    appId: '1:923303506544:web:3b65081dc0cc4a4d557ab5',
    messagingSenderId: '923303506544',
    projectId: 'ecommerce-db570',
    authDomain: 'ecommerce-db570.firebaseapp.com',
    storageBucket: 'ecommerce-db570.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC8o3D1BkO273ljUrvQKTMSbALeJXzmBok',
    appId: '1:923303506544:android:64dc9be9419ab1d3557ab5',
    messagingSenderId: '923303506544',
    projectId: 'ecommerce-db570',
    storageBucket: 'ecommerce-db570.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCItMVmrPrBBL1owZGFgIx36psiZM92hyk',
    appId: '1:923303506544:ios:415884261407af0a557ab5',
    messagingSenderId: '923303506544',
    projectId: 'ecommerce-db570',
    storageBucket: 'ecommerce-db570.appspot.com',
    iosBundleId: 'com.example.eCommerce',
  );
}
